import { Task, Subject, ScheduleItem, StudentProfile } from '../types';

export interface GeneratedScheduleResult {
  schedule: ScheduleItem[];
  totalAllocatedMinutes: number;
  unassignedTasks: Task[];
}

/**
 * Algoritma Smart Study Scheduler
 * Menghitung Priority Index (PI) untuk setiap tugas:
 * PI = (UrgencyScore * 0.35) + (PriorityMatrixScore * 0.35) + (SubjectDifficultyScore * 0.20) + (RemainingTimeScore * 0.10)
 */
export function generateSmartSchedule(
  tasks: Task[],
  subjects: Subject[],
  profile: StudentProfile,
  startDate: Date = new Date(),
  daysToPlan: number = 7
): GeneratedScheduleResult {
  const subjectMap = new Map<string, Subject>();
  subjects.forEach((s) => subjectMap.set(s.id, s));

  // 1. Filter tugas yang belum selesai
  const activeTasks = tasks.filter((t) => t.status !== 'COMPLETED');

  // 2. Hitung Priority Score untuk tiap tugas
  const scoredTasks = activeTasks.map((task) => {
    const subject = subjectMap.get(task.subjectId);
    const difficultyScore = subject ? subject.difficultyLevel : 3;

    // Sisa estimasi menit
    const remainingMinutes = Math.max(15, task.estimatedMinutes - task.completedMinutes);

    // Hitung sisa hari ke deadline
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const due = new Date(task.dueDate);
    due.setHours(0, 0, 0, 0);
    const diffDays = Math.max(0, Math.ceil((due.getTime() - today.getTime()) / (1000 * 3600 * 24)));

    let urgencyScore = 1;
    if (diffDays === 0) urgencyScore = 10;
    else if (diffDays === 1) urgencyScore = 8;
    else if (diffDays <= 3) urgencyScore = 6;
    else if (diffDays <= 7) urgencyScore = 4;
    else urgencyScore = 2;

    let priorityMatrixScore = 1;
    switch (task.priority) {
      case 'HIGH_URGENT':
        priorityMatrixScore = 10;
        break;
      case 'HIGH_NOT_URGENT':
        priorityMatrixScore = 7;
        break;
      case 'LOW_URGENT':
        priorityMatrixScore = 5;
        break;
      case 'LOW_NOT_URGENT':
        priorityMatrixScore = 3;
        break;
    }

    const totalPriorityIndex =
      urgencyScore * 0.35 +
      priorityMatrixScore * 0.35 +
      difficultyScore * 2 * 0.20 +
      Math.min(10, remainingMinutes / 30) * 0.10;

    return {
      task,
      remainingMinutes,
      priorityIndex: totalPriorityIndex,
    };
  });

  // Urutkan tugas berdasarkan Priority Index tertinggi
  scoredTasks.sort((a, b) => b.priorityIndex - a.priorityIndex);

  // Waktu Mulai Belajar Default Berdasarkan Peak Time
  let startHour = 18;
  let startMinute = 30;
  if (profile.peakProductiveTime === 'MORNING') {
    startHour = 7;
    startMinute = 0;
  } else if (profile.peakProductiveTime === 'AFTERNOON') {
    startHour = 14;
    startMinute = 0;
  } else if (profile.peakProductiveTime === 'EVENING') {
    startHour = 18;
    startMinute = 30;
  } else if (profile.peakProductiveTime === 'NIGHT') {
    startHour = 20;
    startMinute = 0;
  }

  const newSchedule: ScheduleItem[] = [];
  const dailyQuotaMinutes = Math.round((profile.dailyStudyTargetHours || 3) * 60);
  let totalAllocatedMinutes = 0;

  // Clone list scored tasks untuk pengalokasian
  const taskPool = scoredTasks.map((st) => ({ ...st }));

  for (let dayOffset = 0; dayOffset < daysToPlan; dayOffset++) {
    const currentDate = new Date(startDate);
    currentDate.setDate(currentDate.getDate() + dayOffset);
    const dateStr = currentDate.toISOString().split('T')[0];

    let minutesAllocatedToday = 0;
    let currentSlotHour = startHour;
    let currentSlotMin = startMinute;

    for (const item of taskPool) {
      if (item.remainingMinutes <= 0) continue;
      if (minutesAllocatedToday >= dailyQuotaMinutes) break;

      // Alokasikan per blok Pomodoro (misal 30-45 menit per sesi)
      const sessionBlock = Math.min(45, item.remainingMinutes, dailyQuotaMinutes - minutesAllocatedToday);

      if (sessionBlock < 15) continue;

      const formatTime = (h: number, m: number) => {
        const hh = String(h).padStart(2, '0');
        const mm = String(m).padStart(2, '0');
        return `${hh}:${mm}`;
      };

      const startTimeStr = formatTime(currentSlotHour, currentSlotMin);

      // Hitung end time
      let endSlotMin = currentSlotMin + sessionBlock;
      let endSlotHour = currentSlotHour;
      if (endSlotMin >= 60) {
        endSlotHour += Math.floor(endSlotMin / 60);
        endSlotMin = endSlotMin % 60;
      }
      const endTimeStr = formatTime(endSlotHour, endSlotMin);

      newSchedule.push({
        id: `sched-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
        title: `Belajar: ${item.task.title}`,
        subjectId: item.task.subjectId,
        taskId: item.task.id,
        date: dateStr,
        startTime: startTimeStr,
        endTime: endTimeStr,
        isAutoGenerated: true,
        completed: false,
      });

      minutesAllocatedToday += sessionBlock;
      totalAllocatedMinutes += sessionBlock;
      item.remainingMinutes -= sessionBlock;

      // Update slot berikutnya (+10 menit istirahat)
      currentSlotMin = endSlotMin + 10;
      currentSlotHour = endSlotHour;
      if (currentSlotMin >= 60) {
        currentSlotHour += Math.floor(currentSlotMin / 60);
        currentSlotMin = currentSlotMin % 60;
      }
    }
  }

  const unassignedTasks = taskPool
    .filter((tp) => tp.remainingMinutes > 0)
    .map((tp) => tp.task);

  return {
    schedule: newSchedule,
    totalAllocatedMinutes,
    unassignedTasks,
  };
}
