export type Priority = 'HIGH_URGENT' | 'HIGH_NOT_URGENT' | 'LOW_URGENT' | 'LOW_NOT_URGENT';

export type TaskStatus = 'PENDING' | 'IN_PROGRESS' | 'COMPLETED';

export type AcademicTrack = 'SAINTEK' | 'AGAMA' | 'BAHASA' | 'EKONOMI' | 'KESEHATAN' | 'UMUM';

export interface Subject {
  id: string;
  code: string;
  name: string;
  teacherName: string;
  targetGrade: number; // e.g. 90
  color: string; // Tailwind hex or class name
  difficultyLevel: 1 | 2 | 3 | 4 | 5; // 1 = Sangat Mudah, 5 = Sangat Sulit
  weeklyTargetHours: number; // Jam
  track?: AcademicTrack;
}

export interface Task {
  id: string;
  title: string;
  subjectId: string;
  dueDate: string; // ISO date string
  estimatedMinutes: number;
  completedMinutes: number;
  priority: Priority;
  status: TaskStatus;
  description?: string;
  tags: string[];
  createdAt: string;
}

export interface StudySession {
  id: string;
  taskId?: string;
  subjectId: string;
  startTime: string; // ISO string
  endTime: string; // ISO string
  durationMinutes: number;
  mode: 'POMODORO' | 'STOPWATCH' | 'MANUAL';
  comprehensionRating: 1 | 2 | 3 | 4 | 5; // Rating pemahaman materi
  notes?: string;
}

export interface ScheduleItem {
  id: string;
  title: string;
  subjectId: string;
  taskId?: string;
  date: string; // YYYY-MM-DD
  startTime: string; // HH:mm
  endTime: string; // HH:mm
  isAutoGenerated: boolean;
  completed: boolean;
}

export interface StudyGoal {
  id: string;
  title: string;
  targetMinutesPerWeek: number;
  currentMinutesThisWeek: number;
  startDate: string;
  endDate: string;
}

export interface HobbyActivity {
  id: string;
  title: string;
  category: 'OLAHRAGA' | 'SENI' | 'AGAMA' | 'SAINTEK_ROBOTIK' | 'KESEHATAN_PMR' | 'LITERASI' | 'LAINNYA';
  weeklyTarget: string;
  notes?: string;
  completedThisWeek: boolean;
}

export interface StudentProfile {
  name: string;
  schoolName: string;
  gradeClass: string;
  academicTrack: AcademicTrack;
  hobbies: string[]; // e.g. ["Olahraga/Futsal", "Kajian & Tahfidz", "Robotik"]
  dailyStudyTargetHours: number;
  peakProductiveTime: 'MORNING' | 'AFTERNOON' | 'EVENING' | 'NIGHT';
}

export type UserRole = 'STUDENT' | 'ADMIN';

export type UserAccountStatus = 'ACTIVE' | 'SUSPENDED';

export interface UserAccount {
  id: string;
  email: string;
  name: string;
  role: UserRole;
  passwordHash: string; // Hashed/encoded for mock security
  status: UserAccountStatus;
  schoolName?: string;
  gradeClass?: string;
  createdAt: string;
  lastLoginAt?: string;
}

export interface AuthSession {
  token: string;
  userId: string;
  email: string;
  name: string;
  role: UserRole;
  loginTime: string;
  expiresAt: string;
}

export interface Announcement {
  id: string;
  title: string;
  content: string;
  type: 'INFO' | 'WARNING' | 'IMPORTANT';
  createdAt: string;
  createdBy: string;
  active: boolean;
}

export interface SecurityAuditLog {
  id: string;
  timestamp: string;
  action: string;
  userEmail: string;
  role: string;
  status: 'SUCCESS' | 'FAILED' | 'BLOCKED';
  ipAddress: string;
  details?: string;
}

export interface DirectStudentMessage {
  id: string;
  recipientEmail: string; // 'ALL' or specific student email
  senderName: string;
  subject: string;
  body: string;
  isRead: boolean;
  createdAt: string;
  priority: 'NORMAL' | 'HIGH';
}

